---
- name: Get Active Directory top level Organizational Units
  hosts: domctls
  gather_facts: yes
  collections:
    - ansible.windows

  
  tasks:
    - name: Retrieve OU structure
      win_powershell:
        script: |
          Get-ADOrganizationalUnit -Filter * | Select-Object DistinguishedName | ConvertTo-JSON
      register: script_output
      when: inventory_hostname == groups['domctls'][0]
      
    - name: Show output
      debug:
        var: script_output.stdout
