---
- name: Install and promote the first domain controller
  hosts: domctls
  gather_facts: no
  collections:
    - ansible.windows

  
  tasks:
    - name: Install ADDS role and management tools
      win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: true
      register: feature_install
    
    - name: Promote first domain controller and create forest
      win_powershell:
        script: |
          $domainParams = @{
            DomainName = 'example.com'
            DomainNetbiosName = 'EXAMPLE'
            ForestMode = 'Win2025'
            DomainMode = 'Win2025'
            CreateDnsDelegation = $false
            InstallDns = $true
            Force = $true
          }
          $DSRMpassword = ConvertTo-SecureString 'Ex@mpledotcom!!!123' -AsPlainText -Force
          Install-ADDSForest @domainParams -SafeModeAdministratorPassword $DSRMpassword
      when: inventory_hostname == groups['domctls'][0]
